# Generated by Django 2.2 on 2019-05-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemId', models.IntegerField()),
                ('Repeat', models.IntegerField()),
                ('DateCreated', models.DateTimeField()),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsDone', models.BooleanField(default=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'todo item',
            },
        ),
        migrations.CreateModel(
            name='ItemContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContentId', models.IntegerField()),
                ('Content', models.TextField()),
                ('Title', models.CharField(default='', max_length=256)),
                ('DateCreated', models.DateTimeField()),
                ('TagId', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.ItemInfo')),
            ],
            options={
                'verbose_name': 'todo item content',
            },
        ),
    ]
